const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ts=require(path.join(process.cwd(),'node_modules/typescript')),cache=new Map();
function load(relative){const filename=path.resolve(relative);if(cache.has(filename))return cache.get(filename).exports;const module={exports:{}};cache.set(filename,module);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>load(path.resolve(path.dirname(filename),id)+'.ts'),module,module.exports);return module.exports;}
let stored;global.localStorage={getItem:()=>stored,setItem:(_k,v)=>stored=v};global.document={querySelector:()=>null};
const {AlleyEventManager:M}=load('src/systems/AlleyEventManager.ts'),{newSave,SaveManager:S}=load('src/systems/SaveManager.ts'),{alleyEvents:E}=load('src/data/alleyEvents.ts');
function save(){const s=newSave();s.gold=100;s.night=20;s.unlockedRecipes=['rice','oden','milk','ramen','bread'];for(const p of Object.values(s.customers)){p.unlocked=true;p.visitCount=20;p.intimacy=50;p.storyStage=3;if(p.characterStory)p.characterStory.stage=6;}s.customers.nabi.characterStory.stage=3;s.activeNight={queue:Array(5).fill('ambient_seol'),pairStarts:[],condition:'ordinary',report:{served:1,gold:0,perfect:0,intimacy:{},discoveries:[]}};return s;}
function reserve(s,id){const pool=E.filter(e=>M.eligible(s,e)&&!s.recentAlleyEventIds?.includes(e.id));const at=pool.findIndex(e=>e.id===id);assert(at>=0);const total=pool.reduce((n,e)=>n+M.weight(s,e),0),before=pool.slice(0,at).reduce((n,e)=>n+M.weight(s,e),0);let call=0;return M.tryReserve(s,()=>call++===0?0:(before+M.weight(s,pool[at])/2)/total);}
assert.equal(E.length,10);assert.equal(new Set(E.map(e=>e.id)).size,10);
for(const e of E){for(const choice of e.choices??[{id:'observe',gold:0}]){
 let s=save();s.weather='rain';const characters=structuredClone(s.customers),recipes=[...s.unlockedRecipes];assert.equal(reserve(s,e.id).id,e.id);S.save(s);s=S.load();assert.equal(M.pending(s).id,e.id);const result=M.result(s,choice.id);assert.equal(result.id,choice.id);const gold=100+(choice.gold??0);assert.equal(s.gold,gold);assert.equal(s.activeNight.report.gold,choice.gold??0);S.save(s);s=S.load();M.result(s,'other');assert.equal(s.gold,gold);assert(M.complete(s));assert(!M.complete(s));assert.deepEqual(s.customers,characters);assert.deepEqual(s.unlockedRecipes,recipes);assert.equal(s.activeNight.report.served,1);if(e.once){assert(s.completedAlleyEvents.includes(e.id));assert(!M.eligible(s,e));}assert.equal(M.tryReserve(s,()=>0),undefined);S.save(s);s=S.load();assert.equal(s.gold,gold);assert.equal(M.pending(s),undefined);
}}
let s=save();s.activeNight.report.served=0;assert.equal(M.tryReserve(s,()=>0),undefined);s.activeNight.report.served=1;s.activeNight.queue[1]='nabi';s.customers.nabi.characterStory.stage=0;assert.equal(M.tryReserve(s,()=>0),undefined);assert.equal(s.activeNight.alley,undefined);s.activeNight.queue[1]='ambient_seol';s.customers.nabi.characterStory.pending={eventId:'NABI_STORY_1',part:'before',line:0,visit:21,night:20};assert.equal(M.tryReserve(s,()=>0),undefined);
s=save();assert.equal(M.tryReserve(s,()=>1),undefined);S.save(s);s=S.load();assert.equal(M.tryReserve(s,()=>0),undefined);s.activeNight.report.served=3;assert.equal(M.tryReserve(s,()=>1),undefined);s.activeNight.report.served=5;assert.equal(M.tryReserve(s,()=>0),undefined);assert.deepEqual(s.activeNight.alley.checks,[1,3]);
s=save();s.customers.dubu.unlocked=false;assert(!M.eligible(s,E.find(e=>e.id==='dubu_dig')));s.customers.nabi.characterStory.stage=2;assert(!M.eligible(s,E.find(e=>e.id==='nabi_alley_wait')));s.customers.nabi.characterStory.stage=6;assert(!M.eligible(s,E.find(e=>e.id==='nabi_alley_wait')));
s=save();const kitten=E.find(e=>e.id==='rain_kitten');const clear=M.weight(s,kitten);s.weather='rain';s.activeNight.condition='shower';assert(M.weight(s,kitten)>clear*3);s.weather='snow';s.activeNight.condition='cold';assert(M.weight(s,kitten)<clear);
for(const version of [1,2]){s=save();s.version=version;s.gold=987;s.weather='snow';delete s.completedAlleyEvents;delete s.recentAlleyEventIds;stored=JSON.stringify(s);const r=S.load();assert.equal(r.gold,987);assert.equal(r.weather,'snow');assert.deepEqual(r.customers,s.customers);assert.deepEqual(r.completedAlleyEvents,[]);assert.deepEqual(r.recentAlleyEventIds,[]);}
assert.deepEqual(M.restore({checks:[-1,'x',1,1,3,9],seenIds:['bad','fallen_tin'],pending:{eventId:'bad',choiceId:'x'}},5),{checks:[1,3],seenIds:['fallen_tin']});
let seed=9007;const rng=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};const counts=[0,0,0];let history=[],completed=[];
for(let night=0;night<10000;night++){s=save();s.recentAlleyEventIds=history.slice();s.completedAlleyEvents=completed.slice();for(let served=1;served<=5;served++){s.activeNight.report.served=served;const previous=history.slice(),event=M.tryReserve(s,rng);if(!event)continue;assert(!previous.includes(event.id));M.result(s,event.choices?.[0].id??'observe');M.complete(s);history=s.recentAlleyEventIds;completed=s.completedAlleyEvents??[];}const ids=s.activeNight.alley?.seenIds??[];assert(ids.length<=2);assert.equal(new Set(ids).size,ids.length);counts[ids.length]++;}
const average=(counts[1]+2*counts[2])/10000;assert(average>.85&&average<.95);console.log('PASS alley: all 18 outcomes, history5, cap2, once, choice/reload gold once, story priority, weather weights, v1/v2 migration; 10,000-night frequency',counts,'average',average.toFixed(3));
