const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ts=require(path.join(process.cwd(),'node_modules/typescript'));
const cache=new Map();
function load(relative){const filename=path.resolve(relative);if(cache.has(filename))return cache.get(filename).exports;const module={exports:{}};cache.set(filename,module);const code=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',code)(id=>load(path.resolve(path.dirname(filename),id)+'.ts'),module,module.exports);return module.exports;}
let stored;global.localStorage={getItem:()=>stored,setItem:(_k,value)=>{stored=value}};global.document={querySelector:()=>null};
const {CharacterStoryManager:M}=load('src/systems/CharacterStoryManager.ts');const {SaveManager:S,newSave}=load('src/systems/SaveManager.ts');const {DialogueManager:D}=load('src/systems/DialogueManager.ts');const {ProgressionManager:P}=load('src/systems/ProgressionManager.ts');
for(const version of [1,2]){const s=newSave();s.version=version;s.gold=789;s.level=6;s.night=24;s.weather='snow';s.unlockedRecipes=['rice','oden','milk','ramen','bread'];s.upgrades={chair:1,pot:1};s.customers.nabi={intimacy:100,visitCount:45,unlocked:true,preferenceFound:true,storyStage:3};stored=JSON.stringify(s);const restored=S.load();assert.equal(restored.gold,789);assert.equal(restored.night,24);assert.equal(restored.weather,'snow');assert.deepEqual(restored.unlockedRecipes,s.unlockedRecipes);assert.equal(restored.customers.nabi.intimacy,100);assert.equal(restored.customers.nabi.storyStage,3);assert.equal(restored.customers.nabi.characterStory.stage,0);assert.equal(M.reserve('nabi',restored.customers.nabi,24).id,'NABI_STORY_1');}
let s=newSave(),p=s.customers.nabi;p.visitCount=30;p.intimacy=200;M.reserve('nabi',p,1);M.advance('nabi',p);S.save(s);s=S.load();p=s.customers.nabi;assert.equal(p.characterStory.pending.line,1);while(p.characterStory.pending)M.advance('nabi',p);assert.equal(M.reserve('nabi',p,1),undefined);p.visitCount=31;assert.equal(M.reserve('nabi',p,2),undefined);p.visitCount=32;assert.equal(M.reserve('nabi',p,1),undefined);assert.equal(M.reserve('nabi',p,2).id,'NABI_STORY_2');while(p.characterStory.pending)M.advance('nabi',p);assert(p.preferenceFound);
// Visits alone cannot open an intimacy-gated event.
p.characterStory={stage:2,lastEventVisit:3,lastEventNight:1};p.visitCount=10;p.intimacy=7;assert.equal(M.reserve('nabi',p,2),undefined);p.intimacy=8;assert.equal(M.reserve('nabi',p,2).id,'NABI_STORY_3');
// Split ending and refresh after serving retain the same event, without paying twice.
s=newSave();p=s.customers.nabi;p.visitCount=12;p.intimacy=40;p.characterStory={stage:5,lastEventVisit:10,lastEventNight:4};s.night=5;s.activeNight={queue:['nabi'],report:{served:0,gold:0,perfect:0,intimacy:{},discoveries:[]}};M.reserve('nabi',p,5);while(p.characterStory.pending.part==='before')M.advance('nabi',p);assert.equal(p.characterStory.stage,5);assert.equal(p.characterStory.pending.part,'after');P.serve(s,'nabi','완벽','');let loaded=S.load();assert.equal(loaded.gold,15);assert.equal(loaded.activeNight.report.served,1);assert.equal(loaded.customers.nabi.characterStory.pending.eventId,'NABI_STORY_COMPLETE');assert.equal(loaded.customers.nabi.characterStory.pending.visit,13);while(loaded.customers.nabi.characterStory.pending)M.advance('nabi',loaded.customers.nabi);S.save(loaded);loaded=S.load();assert(M.complete('nabi',loaded.customers.nabi));assert.equal(M.reserve('nabi',loaded.customers.nabi,6),undefined);assert.equal(loaded.gold,15);
// Missing or malformed story state cannot erase an otherwise valid save.
for(const raw of [undefined,null,{stage:-1},{stage:'six'},{stage:0,pending:{eventId:'bad',part:'before',line:0,visit:1,night:1}},{stage:0,pending:{eventId:'NABI_STORY_1',part:'before',line:999,visit:1,night:1}}]){s=newSave();s.gold=555;s.customers.nabi.characterStory=raw;stored=JSON.stringify(s);loaded=S.load();assert.equal(loaded.gold,555);assert.equal(loaded.customers.nabi.characterStory.stage,0);assert.equal(loaded.customers.nabi.characterStory.pending,undefined);}
s=newSave();const dubu=s.customers.dubu;dubu.visitCount=5;dubu.intimacy=10;assert(D.unlock('dubu',dubu).length>0);assert.equal(dubu.storyStage,1);assert(dubu.preferenceFound);assert.equal(dubu.characterStory,undefined);
console.log('PASS model: v1/v2 save migration, high affinity start, visit/night/intimacy gates, cursor persistence, split ending, malformed fields, completion/no repeat, unchanged legacy customer unlock');
