const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ts=require(path.join(process.cwd(),'node_modules/typescript')),cache=new Map();
function load(relative){const filename=path.resolve(relative);if(cache.has(filename))return cache.get(filename).exports;const module={exports:{}};cache.set(filename,module);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>load(path.resolve(path.dirname(filename),id)+'.ts'),module,module.exports);return module.exports;}
let stored;global.localStorage={getItem:()=>stored,setItem:(_k,v)=>stored=v};global.document={querySelector:()=>null};
const G=load('src/game/DubuDigGame.ts'),{AlleyEventManager:M}=load('src/systems/AlleyEventManager.ts'),{newSave,SaveManager:S}=load('src/systems/SaveManager.ts');
for(const target of [0,1,2])for(const treasure of ['button','cap','stone'])for(const first of [0,1,2])for(const second of [0,1,2]){
 let s=newSave();s.gold=500;s.night=20;s.activeNight={queue:['dubu','ambient_seol'],report:{served:1,gold:15,perfect:1,intimacy:{dubu:3},discoveries:[]},alley:{checks:[1],seenIds:['dubu_dig'],pending:{eventId:'dubu_dig',choiceId:'help',dig:{target,treasure,found:false}}}};
 const characters=structuredClone(s.customers);assert.equal(M.dig(s,-1).sniffed,undefined);M.dig(s,first);assert(!M.complete(s));S.save(s);s=S.load();assert.equal(M.dig(s).sniffed,first);assert.equal(M.dig(s).treasure,treasure);M.dig(s,second);if(!M.dig(s).found){assert.equal(M.dig(s).missed,second);M.dig(s,target);}assert(M.dig(s).found);const found=structuredClone(M.dig(s));M.dig(s,0);assert.deepEqual(M.dig(s),found);S.save(s);s=S.load();assert.deepEqual(M.dig(s),found);assert.equal(s.gold,500);assert.deepEqual(s.customers,characters);assert(M.complete(s));assert(!M.complete(s));assert.equal(M.dig(s),undefined);
}
assert.equal(G.restoreDubuDig({target:0,treasure:'toString'}),undefined);assert.equal(G.restoreDubuDig({target:5,treasure:'cap'}),undefined);assert.deepEqual(G.restoreDubuDig({target:0,treasure:'cap',found:true,missed:1}),{target:0,treasure:'cap',found:false});
const s=newSave();s.activeNight={queue:['dubu'],report:{served:1,gold:0,perfect:0,intimacy:{},discoveries:[]},alley:{checks:[1],seenIds:['dubu_dig'],pending:{eventId:'dubu_dig',choiceId:'call'}}};assert.equal(M.dig(s),undefined);assert(M.complete(s));console.log('PASS Dubu dig: 81 routes, 2-3 taps, all three treasures, save/reload each stage, one completion, unchanged character/gold, invalid state, call branch');
