const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript'),cache=new Map(),handlers=new Map();let html='',stored;const ui={modal:v=>{html=v;handlers.clear()},on:(id,fn)=>handlers.set(id,fn),closeModal:()=>{html=''}};
function load(relative){const f=path.resolve(relative);if(f.endsWith('/ui/UI.ts'))return ui;if(cache.has(f))return cache.get(f).exports;const m={exports:{}};cache.set(f,m);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>load(path.resolve(path.dirname(f),id)+'.ts'),m,m.exports);return m.exports;}
global.localStorage={getItem:()=>stored,setItem:(_k,v)=>stored=v};global.document={querySelector:()=>null};
const {newSave,SaveManager:S,emptyReport}=load('src/systems/SaveManager.ts'),{FestivalManager:F}=load('src/systems/FestivalManager.ts'),{ProgressionManager:P}=load('src/systems/ProgressionManager.ts'),{MemoryAlbum:A}=load('src/ui/MemoryAlbum.ts'),{FestivalNotes:UI}=load('src/ui/FestivalNotes.ts'),{festivalEvent}=load('src/data/festival.ts');
let s=newSave();assert.equal(F.ensure(s),undefined);s.night=5;F.ensure(s);assert.equal(s.festival.stage,'food');s.activeNight={queue:['nabi','dubu','ambient_seol','mongsil','kong'],report:emptyReport()};
F.record(s,'nabi',{recipeId:'rice',score:74});assert.equal(s.festival.foodMeals,0);F.record(s,'dubu',{recipeId:'oden',score:100});assert.equal(s.festival.foodMeals,0,'queue guard');
F.record(s,'nabi',{recipeId:'rice',score:75});F.record(s,'nabi',{recipeId:'rice',score:100});assert.equal(s.festival.foodMeals,1,'same meal counts once');P.serve(s,'nabi','맛있음','',{recipeId:'rice',score:80});assert.equal(s.festival.foodMeals,1);P.serve(s,'dubu','맛있음','',{recipeId:'oden',score:80});P.serve(s,'ambient_seol','맛있음','',{recipeId:'rice',score:80});P.serve(s,'mongsil','맛있음','',{recipeId:'milk',score:80});assert.equal(s.festival.foodMeals,4);F.closeNight(s);assert.equal(s.festival.stage,'food','finish all guests before stage advance');P.serve(s,'kong','맛있음','',{recipeId:'rice',score:80});F.closeNight(s);assert.equal(s.festival.stage,'invite');F.closeNight(s);assert.equal(s.festival.stage,'invite');S.save(s);s=S.load();assert.equal(s.festival.stage,'invite');
for(const id of ['nabi','dubu','kong']){s.customers[id].unlocked=true;s.customers[id].intimacy=4}assert(!F.invite(s,'donggu'));assert(F.invite(s,'nabi'));assert(!F.invite(s,'nabi'));assert(F.invite(s,'dubu'));assert(F.invite(s,'kong'));assert(!F.invite(s,'mongsil'));F.closeNight(s);assert.equal(s.festival.stage,'invite','one stage per night');s.night++;s.activeNight={queue:['nabi'],report:{...emptyReport(),served:1}};F.closeNight(s);assert.equal(s.festival.stage,'decorate');s.gold=39;assert(!F.decorate(s));s.gold=40;assert(F.decorate(s));assert.equal(s.gold,0);assert(!F.decorate(s));s.night++;s.activeNight={queue:['nabi'],report:{...emptyReport(),served:1}};F.closeNight(s);assert.equal(s.festival.stage,'ready');assert.equal(s.festival.celebrationNight,8);const q=['donggu','ambient_seol','ambient_kkomi','ambient_haru','ambient_boksil'];assert(!F.openNight(s,q));s.night++;s.activeNight=null;assert(F.openNight(s,q));assert(q.includes('nabi')&&q.includes('dubu')&&q.includes('kong'));assert.equal(q[0],'donggu','existing story guest preserved');assert(!F.openNight(s,q),'celebration scheduled once');s.activeNight={queue:q,festivalNight:true,report:emptyReport()};assert(!F.complete(s));s.activeNight.report.served=q.length;s.festival.finaleLine=3;S.save(s);s=S.load();assert(s.activeNight.festivalNight);assert.equal(s.festival.finaleLine,3,'finale reader resumes');const gold=s.gold;assert(F.complete(s));assert.equal(s.gold,gold+100);assert.equal(s.activeNight.report.gold,100);assert(!F.complete(s));assert.equal(s.gold,gold+100);assert(A.memories(s).some(m=>m.title==='골목에 불빛이 모인 밤'));const event=festivalEvent(s.festival.invited);assert.equal(event.after.length,5);assert(event.after.some(l=>l.text.startsWith('콩이:')));assert(!event.after.some(l=>l.text.startsWith('동구:')),'finale uses invited friends');S.save(s);s=S.load();assert.equal(s.festival.stage,'complete');assert.equal(s.gold,gold+100);assert.equal(s.activeNight.report.gold,100);assert(!F.complete(s),'completion reload does not repay');
assert.equal(F.restore({stage:'bad'}),undefined);assert.equal(F.restore({stage:'ready',invited:[],decorated:true}),undefined);s=newSave();s.night=5;F.ensure(s);let changes=0;UI.open(s,()=>changes++);assert(html.includes('75점'));s.festival.stage='invite';s.customers.nabi.unlocked=true;s.customers.nabi.intimacy=4;UI.open(s,()=>changes++);handlers.get('festival-invite-nabi')();assert.deepEqual(s.festival.invited,['nabi']);assert.equal(changes,1);assert(html.includes('초대 완료'));s.festival.stage='decorate';s.gold=50;UI.open(s,()=>changes++);handlers.get('festival-craft')();assert.equal(s.gold,10);assert(html.includes('축제 장식 완성'));handlers.get('festival-close')();assert.equal(html,'');
for(const version of [1,2]){s=newSave();s.version=version;s.night=20;s.gold=333;stored=JSON.stringify(s);s=S.load();assert.equal(s.gold,333);assert.equal(s.festival.stage,'food');assert.equal(s.festival.foodMeals,0)}
const {FestivalView}=load('src/game/FestivalView.ts');const art=[],tweens=[];class Graphic{constructor(){this.active=true}setDepth(){return this}setName(){return this}fillStyle(){return this}fillRect(){return this}fillTriangle(){return this}fillCircle(){return this}lineStyle(){return this}beginPath(){return this}moveTo(){return this}lineTo(){return this}strokePath(){return this}destroy(){this.active=false}}const scene={add:{graphics(){const g=new Graphic();art.push(g);return g}},tweens:{add(){const t={active:true,stop(){this.active=false},remove(){this.active=false}};tweens.push(t);return t}}};const view=new FestivalView(scene);s.festival.stage='celebrating';for(let i=0;i<10;i++)view.apply(s);assert.equal(art.filter(g=>g.active).length,1);assert.equal(tweens.filter(t=>t.active).length,1);s.festival.stage='complete';view.apply(s);assert.equal(tweens.filter(t=>t.active).length,0);assert.equal(art.filter(g=>g.active).length,1,'permanent keepsake only');view.destroy();assert.equal(art.filter(g=>g.active).length,0);
console.log('PASS festival: unlock, scoring and duplicate gates, four-night stages, invited friends, craft cost once, queue story preservation, finale cursor and one payout, album, UI actions, old saves');
