const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');const cache=new Map(),handlers=new Map();let stored,html='';const ui={modal:s=>{html=s;handlers.clear()},on:(id,f)=>handlers.set(id,f),closeModal:()=>html=''};
function load(relative){const f=path.resolve(relative);if(f.endsWith('/ui/UI.ts'))return ui;if(cache.has(f))return cache.get(f).exports;const m={exports:{}};cache.set(f,m);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>load(path.resolve(path.dirname(f),id)+'.ts'),m,m.exports);return m.exports;}
global.localStorage={getItem:()=>stored,setItem:(_k,v)=>stored=v};global.document={querySelector:()=>null};
const {DecorationManager:M}=load('src/systems/DecorationManager.ts'),{decorations:defs}=load('src/data/decorations.ts'),{SaveManager:S,newSave}=load('src/systems/SaveManager.ts'),{RestaurantDecorView:V}=load('src/game/RestaurantDecorView.ts'),{DecorationShop:UI}=load('src/ui/DecorationShop.ts');
let s=newSave();s.gold=1000;const original=JSON.stringify(s.upgrades);for(const d of defs.filter(d=>d.cost)){assert(!M.equip(s,d.id),'locked skin cannot be equipped');const gold=s.gold;assert(M.buy(s,d.id));assert.equal(s.gold,gold-d.cost);assert.equal(M.style(s,d.slot).id,d.id);assert(!M.buy(s,d.id),'duplicate purchase blocked');assert.equal(s.gold,gold-d.cost);assert(M.equip(s,d.slot+'-basic'));assert(M.equip(s,d.id))}assert.equal(M.count(s),8);assert.equal(JSON.stringify(s.upgrades),original);assert(!M.buy(s,'fake'));assert(!M.buy(s,'lamp-basic'));S.save(s);s=S.load();assert.equal(M.count(s),8);assert.equal(M.style(s,'sign').id,'sign-moon');
const poor=newSave();poor.gold=64;assert(!M.buy(poor,'lamp-moon'));assert.equal(poor.gold,64);assert(M.owns(poor,'lamp-basic'));assert(!M.equip(poor,'missing'));
const sanitized=M.restore({owned:['lamp-moon','lamp-moon','bad'],equipped:{lamp:'lamp-moon',awning:'lamp-moon',seat:'seat-sage',sign:'bad'}});assert.deepEqual(sanitized.owned,['lamp-moon']);assert.equal(sanitized.equipped.lamp,'lamp-moon');assert.equal(sanitized.equipped.awning,'awning-basic');assert.equal(sanitized.equipped.seat,'seat-basic');
for(const version of [1,2]){const old=newSave();old.version=version;old.gold=44;old.upgrades={lamp:1,chair:1,pot:1,sign:1};stored=JSON.stringify(old);const restored=S.load();assert.equal(restored.gold,44);assert.deepEqual(restored.upgrades,old.upgrades);assert.equal(M.style(restored,'awning').id,'awning-basic');assert.equal(M.count(restored),0)}
class Graphic{constructor(){this.commands=[];this.active=true}clear(){this.commands=[];return this}fillStyle(...v){this.commands.push(['color',...v]);return this}fillRect(...v){this.commands.push(['rect',...v]);return this}fillCircle(...v){this.commands.push(['circle',...v]);return this}setName(n){this.name=n;return this}setDepth(d){this.depth=d;return this}destroy(){this.active=false}}
const overlays=[],scene={add:{graphics:()=>{const g=new Graphic();overlays.push(g);return g}}},awning=new Graphic(),board=new Graphic(),title={setFontSize(n){this.size=n;return this},setText(t){this.text=t;return this},setColor(c){this.color=c;return this}},lamps=[{},{}].map(()=>({setFillStyle(c){this.color=c;return this}}));const view=new V(scene,awning,board,title,lamps);
view.apply(s);const paintedCount=awning.commands.length;assert.equal(lamps[0].color,0xefbaa8);assert.equal(title.color,'#dec996');assert(awning.commands.some(c=>c[0]==='rect'&&c[3]===5),'star motif drawn');for(let i=0;i<30;i++)view.apply(s);assert.equal(overlays.filter(o=>o.active).length,1,'one overlay across repeated changes');assert.equal(awning.commands.length,paintedCount,'awning is repainted, not accumulated');
M.equip(s,'lamp-basic');M.equip(s,'seat-basic');M.equip(s,'sign-basic');s.upgrades={lamp:1,chair:1,pot:1,sign:1};view.apply(s);assert.equal(lamps[0].color,0xffd69a);assert.equal(title.text,'길냥이 식당 · 夜');assert(overlays.at(-1).commands.some(c=>c[0]==='rect'&&c[1]===211&&c[2]===738),'legacy cushion retained');view.destroy();assert.equal(overlays.filter(o=>o.active).length,0);
s=newSave();s.gold=100;M.state(s);let changes=0,bindings=0;new UI(s,()=>{changes++;S.save(s)},()=>'<p>시설 효과</p>',()=>bindings++);const baseline=JSON.stringify(s);handlers.get('decor-preview-lamp-moon')();assert(html.includes('달빛 청사초롱 · 미리보기'));assert.equal(JSON.stringify(s),baseline,'preview never spends or equips');handlers.get('decor-select-lamp-moon')();assert.equal(s.gold,35);assert.equal(changes,1);assert.equal(M.style(s,'lamp').id,'lamp-moon');assert(html.includes('사용 중'));handlers.get('decor-select-lamp-basic')();assert.equal(s.gold,35);assert.equal(M.style(s,'lamp').id,'lamp-basic');handlers.get('decor-tab-awning')();assert(html.includes('숲빛 줄무늬'));const before=JSON.stringify(s);handlers.get('decor-select-awning-forest')();assert.equal(JSON.stringify(s),before,'insufficient money guarded by handler');assert(bindings>=4);handlers.get('decor-close')();assert.equal(html,'');
console.log('PASS decor: all 8 purchases, equip locks, duplicate/insufficient funds, save/legacy restoration, upgrade effects retained, preview read-only, live redraw with one overlay, graphics cleanup');
