const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript'),cache=new Map();
function load(relative){const f=path.resolve(relative);if(cache.has(f))return cache.get(f).exports;const m={exports:{}};cache.set(f,m);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>id==='phaser'?{default:{GameObjects:{Container:class{},Image:class{}}}}:load(path.resolve(path.dirname(f),id)+'.ts'),m,m.exports);return m.exports;}
let stored;global.localStorage={getItem:()=>stored,setItem:(_k,v)=>stored=v};global.document={querySelector:()=>null};
const {newSave,SaveManager:S,emptyReport}=load('src/systems/SaveManager.ts'),{RumorManager:R}=load('src/systems/RumorManager.ts'),{RainNightManager:N}=load('src/systems/RainNightManager.ts'),{CustomerManager:C}=load('src/systems/CustomerManager.ts'),{SpecialOrderManager:M}=load('src/systems/SpecialOrderManager.ts'),{ProgressionManager:P}=load('src/systems/ProgressionManager.ts'),{ambientCustomers}=load('src/data/ambientCustomers.ts'),{ambientPixels,ambientBodyPixels,ambientTailPixels}=load('src/game/AmbientArt.ts');
function start(weather='clear',queue=['donggu']){const s=newSave();s.night=20;s.weather=weather;s.unlockedRecipes.push('ramen','bread');s.activeNight={queue,report:emptyReport()};return s}
let s=start();for(let i=0;i<100;i++)assert(!C.queue(s).some(id=>id==='ambient_soli'||id==='ambient_lulu'),'referral guests locked before rumors');
s.customers.donggu={...s.customers.donggu,unlocked:true,intimacy:10,visitCount:3};const o=M.reserve(s,'donggu');const reward=P.serve(s,'donggu','완벽',o.extra,{recipeId:o.recipeId,score:100});assert.equal(reward.specialOrder.referral,'솔이');assert.equal(R.state(s).successes,1);assert.equal(M.resolve(s,'donggu',{recipeId:o.recipeId,score:100},o.extra),undefined);assert.equal(R.state(s).successes,1);
let q=['nabi','dubu','ambient_seol'];assert.deepEqual(R.arrange(s,q),{});s.night++;s.activeNight={queue:q,report:emptyReport(),referrals:R.arrange(s,q)};assert.deepEqual(q,['nabi','dubu','ambient_soli']);assert(R.greeting(s,'ambient_soli').includes('동구'));S.save(s);s=S.load();assert.deepEqual(s.activeNight.referrals,{ambient_soli:'donggu'});assert.equal(R.state(s).pending.length,0);assert.deepEqual(R.arrange(s,q),{});
assert.equal(R.success(s,'nabi'),undefined);assert.equal(R.success(s,'dubu'),'루루');assert.equal(R.success(s,'nabi'),undefined);s.night++;q=['nabi','dubu'];const referral=R.arrange(s,q);assert.equal(q.at(-1),'ambient_lulu','append when no walk-in to replace');assert.equal(q[0],'nabi');assert.equal(referral.ambient_lulu,'dubu');assert.equal(R.state(s).unlocked.length,2);for(let i=0;i<10;i++)R.success(s,'nabi');assert.equal(R.state(s).pending.length,0);
let saw=false;for(let i=0;i<200;i++)if(C.queue(s).includes('ambient_soli'))saw=true;assert(saw,'referred friends can return');for(const id of ['ambient_soli','ambient_lulu']){const c=ambientCustomers.find(c=>c.id===id);assert(ambientPixels(c,false).length);assert(ambientBodyPixels(c,false).length);assert(ambientTailPixels(c).length)}
assert.deepEqual(R.restore({successes:-1,unlocked:['bad','ambient_soli','ambient_soli'],pending:[{id:'ambient_soli',sourceId:'nabi',night:1},{id:'ambient_lulu',sourceId:'bad',night:1}]}),{successes:0,unlocked:['ambient_soli'],pending:[]});
s=start('clear');assert.equal(N.reserve(s,'donggu'),undefined);s.weather='rain';s.customers.donggu.characterStory.pending={eventId:'DONGGU_STORY_1',part:'before',line:0,visit:1,night:20};assert.equal(N.reserve(s,'donggu'),undefined,'story priority');delete s.customers.donggu.characterStory.pending;assert(N.reserve(s,'donggu'));assert.equal(N.reserve(s,'nabi'),undefined,'one shelter event per night');assert.equal(N.finish(s,'donggu','milk'),undefined,'towel first');assert(N.towel(s,'donggu'));assert(!N.towel(s,'donggu'));s.activeNight.rainEvent.shaken=true;S.save(s);s=S.load();assert.equal(N.current(s,'donggu').status,'resting');assert.equal(N.current(s,'donggu').shaken,true);const gold=s.gold;const normal=P.serve(s,'donggu','맛있음','warm',{recipeId:'milk',score:80});assert(normal.rainReaction.includes('귀 끝'));assert.equal(s.activeNight.rainEvent.status,'complete');assert.equal(N.finish(s,'donggu','milk'),undefined);assert.equal(s.gold-gold,normal.gold,'no extra rain currency');S.save(s);s=S.load();assert.equal(N.current(s,'donggu'),undefined);
for(const recipe of ['rice','bread','ramen','oden','milk']){s=start('rain',['ambient_soli']);N.reserve(s,'ambient_soli');N.towel(s,'ambient_soli');const reward=P.serve(s,'ambient_soli','맛있음','',{recipeId:recipe,score:80});assert(reward.rainReaction);assert.equal(reward.intimacy,0);assert.equal(s.activeNight.report.discoveries.filter(d=>d.startsWith('비 오는 밤')).length,1)}
assert.equal(N.restore({customerId:'bad',status:'wet'}),undefined);assert.equal(N.restore({customerId:'nabi',status:'bad'}),undefined);for(const version of [1,2]){s=newSave();s.version=version;s.gold=55;stored=JSON.stringify(s);const old=S.load();assert.equal(old.gold,55);assert.deepEqual(old.alleyRumor,{successes:0,unlocked:[],pending:[]})}
s=newSave();s.night=15;s.specialOrderHistory={donggu:{completed:3,lastNight:14}};stored=JSON.stringify(s);s=S.load();assert.equal(s.alleyRumor.successes,3);assert.equal(s.alleyRumor.pending.length,2,'old special successes retained');S.save(s);s=S.load();assert.equal(s.alleyRumor.pending.length,2,'migration once');
const {CustomerVisit}=load('src/game/CustomerVisit.ts');const visit=Object.create(CustomerVisit.prototype),drops=[],animations=[];visit.guest={x:240,y:729,depth:2,setAngle(v){this.angle=v;return this}};visit.effects=new Set();visit.scene={add:{rectangle(x,y,width,height,color,alpha){const d={x,y,width,height,color,alpha,active:true,setDepth(v){this.depth=v;return this},setName(v){this.name=v;return this},destroy(){this.active=false}};drops.push(d);return d}}};visit.animate=(config,done)=>animations.push({config,done});let ready=0;visit.shakeRain(()=>ready++);assert.equal(drops.length,6);assert(drops.every(d=>d.depth>visit.guest.depth));assert.equal(ready,0,'seating waits for shake');animations.at(-1).done();assert.equal(ready,1);assert.equal(visit.guest.angle,0);for(const a of animations.slice(0,-1))a.done();assert.equal(visit.effects.size,0);assert(drops.every(d=>!d.active),'rain droplets cleaned');
console.log('PASS rumor/rain: special success milestones, two locked/new returning guests and artwork, next-night referrals preserving story positions, save reload and no duplicates, weather/story priority, towel gate, warm/other meal reactions, ambient accounting and old saves');
