const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');const cache=new Map();
function load(relative){const f=path.resolve(relative);if(cache.has(f))return cache.get(f).exports;const m={exports:{}};cache.set(f,m);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>load(path.resolve(path.dirname(f),id)+'.ts'),m,m.exports);return m.exports;}
let stored;global.localStorage={getItem:()=>stored,setItem:(_k,v)=>stored=v};global.document={querySelector:()=>null};
const {newSave,SaveManager:S,emptyReport}=load('src/systems/SaveManager.ts'),{SpecialOrderManager:M}=load('src/systems/SpecialOrderManager.ts'),{specialOrders:defs}=load('src/data/specialOrders.ts'),{ProgressionManager:P}=load('src/systems/ProgressionManager.ts'),{CookingManager:C}=load('src/systems/CookingManager.ts');
function start(id='donggu',all=true){const s=newSave();s.night=20;s.unlockedRecipes=all?['rice','oden','milk','ramen','bread']:['rice','oden','milk'];s.customers[id].unlocked=true;s.customers[id].intimacy=10;s.customers[id].visitCount=3;s.activeNight={queue:[id],report:emptyReport()};return s}
for(const def of defs){let s=start(def.customerId);const o=M.reserve(s,def.customerId,()=>.99);assert(o,'first eligible visit guaranteed');assert.equal(o.recipeId,def.recipes[0].id);const meal={recipeId:o.recipeId,score:75};const base=C.reward('맛있음');const reward=P.serve(s,def.customerId,'맛있음',o.extra,meal);assert(reward.specialOrder.success);assert.equal(reward.specialOrder.gold,12);assert.equal(reward.specialOrder.intimacy,3);assert(reward.specialOrder.reaction);assert.equal(reward.gold,base.gold+12+(reward.kitchen?.bonusGold??0));assert.equal(s.activeNight.report.gold,reward.gold);assert.equal(s.gold,reward.gold);assert.equal(reward.intimacy,base.intimacy+3);assert.equal(s.specialOrderHistory[def.customerId].completed,1);assert.equal(M.resolve(s,def.customerId,meal,o.extra),undefined,'no bonus replay');S.save(s);s=S.load();assert.equal(s.activeNight.specialOrders[def.customerId].status,'success');assert.equal(s.specialOrderHistory[def.customerId].completed,1)}
for(const id of ['donggu','kkamang','mongsil','hodu']){const s=start(id,false),o=M.reserve(s,id);assert(s.unlockedRecipes.includes(o.recipeId));assert.notEqual(o.recipeId,defs.find(d=>d.customerId===id).recipes[0].id,'locked recipe fallback')}
for(const [score,extra,recipe] of [[74,'broth','ramen'],[100,'egg','ramen'],[100,'broth','milk'],[NaN,'broth','ramen'],[101,'broth','ramen']]){const s=start();M.reserve(s,'donggu');const reward=P.serve(s,'donggu','맛있음',extra,{recipeId:recipe,score});assert.equal(reward.specialOrder.success,false);assert.equal(reward.specialOrder.gold,0);assert.equal(s.specialOrderHistory.donggu.completed,0);assert.equal(reward.intimacy,C.reward('맛있음').intimacy);assert.equal(s.activeNight.specialOrders.donggu.status,'missed')}
for(const condition of ['visit','intimacy','locked','story','queue']){const s=start();if(condition==='visit')s.customers.donggu.visitCount=2;if(condition==='intimacy')s.customers.donggu.intimacy=9;if(condition==='locked')s.customers.donggu.unlocked=false;if(condition==='story')s.customers.donggu.characterStory.pending={eventId:'DONGGU_STORY_1',part:'before',line:0,visit:4,night:20};if(condition==='queue')s.activeNight.queue=['nabi'];assert.equal(M.reserve(s,'donggu'),undefined);assert.equal(M.reserve(s,'donggu',()=>0),undefined,'same visit does not reroll')}
let s=start();s.specialOrderHistory={donggu:{completed:1,lastNight:19}};assert.equal(M.reserve(s,'donggu',()=>0),undefined,'cooldown');s=start();s.specialOrderHistory={donggu:{completed:1,lastNight:17}};assert.equal(M.reserve(s,'donggu',()=>.4),undefined);S.save(s);s=S.load();assert.equal(M.reserve(s,'donggu',()=>0),undefined,'failed roll persists');s.night++;s.activeNight={queue:['donggu'],report:emptyReport()};assert(M.reserve(s,'donggu',()=>.399));
s=start();s.activeNight.queue=['nabi','donggu'];s.customers.nabi={...s.customers.nabi,unlocked:true,intimacy:10,visitCount:3};let o=M.reserve(s,'donggu');assert.equal(M.reserve(s,'nabi'),undefined,'one special per night');assert.equal(M.resolve(s,'donggu',{recipeId:o.recipeId,score:100},o.extra),undefined,'serving queue guards settlement');[s.activeNight.queue[0],s.activeNight.queue[1]]=[s.activeNight.queue[1],s.activeNight.queue[0]];S.save(s);s=S.load();assert.equal(M.detail(s,'donggu').id,'ramen');o=M.current(s,'donggu');P.serve(s,'donggu','완벽',o.extra,{recipeId:o.recipeId,score:100});assert.equal(s.specialOrderHistory.donggu.completed,1);assert.equal(s.activeNight.report.served,1);
assert.deepEqual(M.restoreHistory({donggu:{completed:-1,lastNight:2},fake:{completed:9,lastNight:2}}),{});assert.deepEqual(M.restoreNight(start(),{donggu:{recipeId:'ramen',extra:'bad',status:'pending'},nabi:null}),{donggu:null,nabi:null});for(const version of [1,2]){s=newSave();s.version=version;s.gold=321;stored=JSON.stringify(s);s=S.load();assert.equal(s.gold,321);assert.deepEqual(s.specialOrderHistory,{})}
console.log('PASS special orders: 9 guests, available recipe fallbacks, visit/affinity/story gates, first guarantee, cooldown and frozen rolls, one per night, paired queue reorder, score/extra checks, stacked gold/affinity accounting, one payout and legacy reload');
